from pathlib import Path
p=Path('/home/ubuntu/repo_update/android/app/src/main/java/com/choui/animatedinventory/MainActivity.java')
s=p.read_text()
s=s.replace('public class MainActivity {\n', 'public class MainActivity {\n  int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}\n')
s=s.replace('box.setPadding(28,20,28,28)', 'box.setPadding(dp(28),dp(20),dp(28),dp(28))')
s=s.replace('new LinearLayout.LayoutParams(0,58,1)', 'new LinearLayout.LayoutParams(0,dp(58),1)')
s=s.replace('gear.setPadding(12,12,12,12)', 'gear.setPadding(dp(12),dp(12),dp(12),dp(12))')
s=s.replace('new LinearLayout.LayoutParams(52,58)', 'new LinearLayout.LayoutParams(dp(52),dp(58))')
s=s.replace('new LinearLayout.LayoutParams(-1,38)', 'new LinearLayout.LayoutParams(-1,dp(38))')
s=s.replace('new LinearLayout.LayoutParams(-1,332)', 'new LinearLayout.LayoutParams(-1,dp(300))')
s=s.replace('new LinearLayout.LayoutParams(-1,58)', 'new LinearLayout.LayoutParams(-1,dp(58))')
s=s.replace('new LinearLayout.LayoutParams(-1,48)', 'new LinearLayout.LayoutParams(-1,dp(48))')
s=s.replace('new LinearLayout.LayoutParams(-1,8)', 'new LinearLayout.LayoutParams(-1,dp(8))')
s=s.replace('new LinearLayout.LayoutParams(-1,42)', 'new LinearLayout.LayoutParams(-1,dp(42))')
s=s.replace('g.setCornerRadius(16)', 'g.setCornerRadius(dp(16))')
s=s.replace('preview.setBackgroundColor(panel)', 'preview.setBackgroundColor(Color.rgb(224,224,224))')
s=s.replace('Bitmap b=Bitmap.createBitmap(352,332,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);float sx=352f/previewMovie.width(),sy=332f/previewMovie.height();', 'int pw=Math.max(1,preview.getWidth()),ph=Math.max(1,preview.getHeight());Bitmap b=Bitmap.createBitmap(pw,ph,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.rgb(224,224,224));float sx=pw/(float)previewMovie.width(),sy=ph/(float)previewMovie.height();')
p.write_text(s)
