package com.choui.animatedinventory;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.provider.DocumentsContract;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity {
  static final int PICK=1, FOLDER=2; Uri gif, outputTree; byte[] result; TextView status, info, folder; Button action; ProgressBar progress;
  int bg=Color.rgb(17,17,17), panel=Color.rgb(27,27,27), text=Color.rgb(226,226,226), dim=Color.rgb(152,152,152);
  public void onCreate(Bundle b){super.onCreate(b); outputTree=getPreferences(0).getString("outputTree","").isEmpty()?null:Uri.parse(getPreferences(0).getString("outputTree",""));
    ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(bg);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(28,26,28,28);scroll.addView(box);
    TextView title=txt("CHOUIUI  •  GIF CONVERTER",20,text);title.setGravity(17);box.addView(title,new LinearLayout.LayoutParams(-1,55));TextView sub=txt("Animated inventory for Minecraft Bedrock",14,dim);sub.setGravity(17);box.addView(sub,new LinearLayout.LayoutParams(-1,38));
    ImageView icon=new ImageView(this);icon.setImageResource(getResources().getIdentifier("ic_launcher","mipmap",getPackageName()));icon.setScaleType(ImageView.ScaleType.CENTER_INSIDE);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,150);ip.bottomMargin=8;box.addView(icon,ip);
    action=button("SELECT GIF");box.addView(action,new LinearLayout.LayoutParams(-1,58));info=txt("No GIF selected",14,dim);info.setGravity(17);box.addView(info,new LinearLayout.LayoutParams(-1,48));
    progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setVisibility(View.INVISIBLE);box.addView(progress,new LinearLayout.LayoutParams(-1,8));status=txt("Waiting for a GIF",12,dim);status.setGravity(17);box.addView(status,new LinearLayout.LayoutParams(-1,42));
    LinearLayout settings=card();TextView head=txt("SETTINGS",11,dim);head.setTypeface(null,1);settings.addView(head);folder=txt(folderName(),13,text);folder.setPadding(0,12,0,8);settings.addView(folder,new LinearLayout.LayoutParams(-1,50));TextView change=txt("Choose output folder",13,dim);settings.addView(change,new LinearLayout.LayoutParams(-1,38));change.setOnClickListener(v->chooseFolder());box.addView(settings,margin());setContentView(scroll);
    action.setOnClickListener(v->{if(gif==null)pickGif();else convert();});
  }
  TextView txt(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}
  Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(Color.WHITE);b.setTypeface(null,1);b.setAllCaps(false);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(42,42,42));g.setCornerRadius(16);b.setBackground(g);return b;}
  LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(18,16,18,14);GradientDrawable g=new GradientDrawable();g.setColor(panel);g.setCornerRadius(18);l.setBackground(g);return l;}
  LinearLayout.LayoutParams margin(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=15;return p;}
  String folderName(){return outputTree==null?"Same folder as GIF": "Custom output folder selected";}
  void pickGif(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/gif");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}
  void chooseFolder(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);startActivityForResult(i,FOLDER);}
  protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK){gif=d.getData();action.setText("CONVERT GIF");info.setText("GIF selected");status.setText("Ready");}else if(r==FOLDER){outputTree=d.getData();getPreferences(0).edit().putString("outputTree",outputTree.toString()).apply();folder.setText(folderName());}}
  void convert(){new ConvertTask().execute();}
  class ConvertTask extends AsyncTask<Void,Void,byte[]>{protected void onPreExecute(){action.setEnabled(false);progress.setVisibility(View.VISIBLE);status.setText("Converting...");}protected byte[] doInBackground(Void...v){try{return makePack();}catch(Exception e){return null;}}protected void onPostExecute(byte[] b){action.setEnabled(true);progress.setVisibility(View.INVISIBLE);if(b==null){status.setText("Could not convert this GIF");return;}result=b;try{saveResult();status.setText("MCPACK saved");}catch(Exception e){status.setText("Could not save the MCPACK");}}}
  void saveResult()throws Exception{String name="Animated Inventory.mcpack";if(outputTree==null){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,3);return;}Uri doc=DocumentsContract.createDocument(getContentResolver(),outputTree,"application/octet-stream",name);try(OutputStream o=getContentResolver().openOutputStream(doc)){o.write(result);}}
  byte[] read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();return out.toByteArray();}
  int gifFrames(byte[] raw){int i=0,n=0;while(i<raw.length){int b=raw[i++]&255;if(b==0x3b)break;if(b==0x2c){if(i+9>raw.length)break;int packed=raw[i+8]&255;i+=9;if((packed&128)!=0)i+=3*(1<<((packed&7)+1));if(i>=raw.length)break;i++;while(i<raw.length){int s=raw[i++]&255;if(s==0)break;i+=s;}n++;}else if(b==0x21){if(i>=raw.length)break;i++;while(i<raw.length){int s=raw[i++]&255;if(s==0)break;i+=s;}}else break;}return Math.max(1,n);}
  byte[] makePack()throws Exception{byte[] raw=read(gif);Movie m=Movie.decodeByteArray(raw,0,raw.length);if(m==null)throw new Exception();int count=Math.min(11,gifFrames(raw)),dur=Math.max(100,m.duration()),fps=Math.max(2,Math.min(30,Math.round(1000f*count/dur)));int w=352,h=332;Bitmap strip=Bitmap.createBitmap(w*count,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(strip);Paint p=new Paint(3);for(int n=0;n<count;n++){m.setTime((int)(dur*n/(float)count));c.save();c.scale((float)w/m.width(),(float)h/m.height());m.draw(c,0,0,p);c.restore();}Bitmap lines=BitmapFactory.decodeStream(getAssets().open("template/textures/ui/inventory_lines.png"));for(int n=0;n<count;n++)c.drawBitmap(lines,null,new Rect(n*w,0,n*w+w,h),p);ByteArrayOutputStream stripOut=new ByteArrayOutputStream();strip.compress(Bitmap.CompressFormat.PNG,100,stripOut);Bitmap icon=Bitmap.createBitmap(256,256,Bitmap.Config.ARGB_8888);Canvas ic=new Canvas(icon);m.setTime(0);ic.scale(256f/m.width(),256f/m.height());m.draw(ic,0,0,p);ByteArrayOutputStream iconOut=new ByteArrayOutputStream();icon.compress(Bitmap.CompressFormat.PNG,100,iconOut);Map<String,byte[]> files=new HashMap<>();loadAssets(files,"template","");files.put("textures/ui/inventory_flipbook.png",stripOut.toByteArray());files.put("pack_icon.png",iconOut.toByteArray());String common=new String(files.get("ui/chouiui/chouiui_common.json"),"UTF-8").replaceAll("\\\"frame_count\\\"\\s*:\\s*\\d+","\\\"frame_count\\\": "+count).replaceAll("\\\"fps\\\"\\s*:\\s*\\d+","\\\"fps\\\": "+fps);files.put("ui/chouiui/chouiui_common.json",common.getBytes("UTF-8"));ByteArrayOutputStream out=new ByteArrayOutputStream();ZipOutputStream z=new ZipOutputStream(out);for(Map.Entry<String,byte[]>e:files.entrySet()){z.putNextEntry(new ZipEntry(e.getKey()));z.write(e.getValue());z.closeEntry();}z.close();return out.toByteArray();}
  void loadAssets(Map<String,byte[]>out,String root,String rel)throws Exception{String[] list=getAssets().list(root+(rel.isEmpty()?"":"/"+rel));for(String s:list){String r=rel.isEmpty()?s:rel+"/"+s;String p=root+"/"+r;String[] sub=getAssets().list(p);if(sub.length>0)loadAssets(out,root,r);else{InputStream in=getAssets().open(p);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);out.put(r,o.toByteArray());}}}
}
