package com.choui.animatedinventory;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.provider.DocumentsContract;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity {
  int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
  static final int PICK=1,FOLDER=2; Uri gif,outputTree; byte[] result; TextView status,info; Button action; ProgressBar progress; ImageView preview; Movie previewMovie; Handler previewHandler=new Handler(Looper.getMainLooper()); int previewTime=0, previewDuration=100,previewStep=100; int bg=Color.rgb(17,17,17),text=Color.rgb(226,226,226),dim=Color.rgb(152,152,152),panel=Color.rgb(27,27,27);
  public void onCreate(Bundle b){super.onCreate(b);String saved=getPreferences(0).getString("outputTree","");outputTree=saved.isEmpty()?null:Uri.parse(saved);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(bg);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(28),dp(20),dp(28),dp(28));scroll.addView(box);
    LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=txt("CHOUIUI  •  GIF CONVERTER",20,text);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,dp(58),1));ImageButton gear=new ImageButton(this);gear.setImageResource(R.drawable.ic_gear);gear.setBackgroundColor(Color.TRANSPARENT);gear.setContentDescription("Export folder");gear.setPadding(dp(12),dp(12),dp(12),dp(12));gear.setOnClickListener(v->chooseFolder());top.addView(gear,new LinearLayout.LayoutParams(dp(52),dp(58)));box.addView(top);
    TextView sub=txt("Animated inventory for Minecraft Bedrock",14,dim);sub.setGravity(17);box.addView(sub,new LinearLayout.LayoutParams(-1,dp(38)));preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);preview.setBackgroundColor(Color.rgb(224,224,224));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(300));ip.bottomMargin=8;box.addView(preview,ip);
    action=button("SELECT GIF");box.addView(action,new LinearLayout.LayoutParams(-1,dp(58)));info=txt("No GIF selected",14,dim);info.setGravity(17);box.addView(info,new LinearLayout.LayoutParams(-1,dp(48)));progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setVisibility(View.INVISIBLE);box.addView(progress,new LinearLayout.LayoutParams(-1,dp(8)));status=txt("Waiting for a GIF",12,dim);status.setGravity(17);box.addView(status,new LinearLayout.LayoutParams(-1,dp(42)));setContentView(scroll);action.setOnClickListener(v->{if(gif==null)pickGif();else convert();});}
  TextView txt(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}
  Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(Color.WHITE);b.setTypeface(null,1);b.setAllCaps(false);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(42,42,42));g.setCornerRadius(dp(16));b.setBackground(g);return b;}
  void pickGif(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/gif","image/*"});i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK);}void chooseFolder(){final EditText path=new EditText(this);path.setText(outputTree==null?"Same folder / system save dialog":"Custom folder selected");path.setTextColor(text);path.setSingleLine(true);path.setPadding(18,12,18,12);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Export folder").setMessage("Choose where converted .mcpack files will be saved.").setView(path).setNegativeButton("Cancel",null).setPositiveButton("Browse",(d,w)->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);startActivityForResult(i,FOLDER);}).create();dialog.show();}
  protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK){gif=d.getData();action.setText("CONVERT GIF");info.setText("GIF selected");status.setText("Loading preview...");new Thread(()->startPreview()).start();}else if(r==FOLDER){outputTree=d.getData();try{getContentResolver().takePersistableUriPermission(outputTree,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}getPreferences(0).edit().putString("outputTree",outputTree.toString()).apply();status.setText("Output folder updated");}else if(r==3){try{if(result!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(result);}status.setText("MCPACK saved");}catch(Exception e){status.setText("Could not save the MCPACK");}}}
  void startPreview(){try{byte[] raw=read(gif);runOnUiThread(()->setupPreview(raw));}catch(Exception e){runOnUiThread(()->status.setText("Could not read this GIF"));}}
  void setupPreview(byte[] raw){try{previewMovie=Movie.decodeByteArray(raw,0,raw.length);if(previewMovie==null||previewMovie.width()<=0||previewMovie.height()<=0)throw new IOException("Unsupported GIF");previewDuration=Math.max(100,previewMovie.duration());previewStep=Math.max(16,previewDuration/Math.max(1,gifFrames(raw)));previewTime=0;status.setText("Ready");previewHandler.removeCallbacksAndMessages(null);previewHandler.post(previewTick);}catch(Exception e){status.setText("Could not read this GIF");}}
  Runnable previewTick=new Runnable(){public void run(){if(previewMovie==null)return;int pw=Math.max(1,preview.getWidth()),ph=Math.max(1,preview.getHeight());Bitmap b=Bitmap.createBitmap(pw,ph,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.rgb(224,224,224));float sx=pw/(float)previewMovie.width(),sy=ph/(float)previewMovie.height();c.scale(sx,sy);previewMovie.setTime(previewTime);previewMovie.draw(c,0,0);preview.setImageBitmap(b);previewTime=(previewTime+previewStep)%previewDuration;previewHandler.postDelayed(this,previewStep);}};
  void convert(){new ConvertTask().execute();}
  class ConvertTask extends AsyncTask<Void,Void,byte[]>{protected void onPreExecute(){action.setEnabled(false);progress.setVisibility(View.VISIBLE);status.setText("Converting...");}protected byte[] doInBackground(Void...v){try{return makePack();}catch(Exception e){return null;}}protected void onPostExecute(byte[] b){action.setEnabled(true);progress.setVisibility(View.INVISIBLE);if(b==null){status.setText("Could not convert this GIF");return;}result=b;try{saveResult();status.setText("MCPACK saved");}catch(Exception e){status.setText("Could not save the MCPACK");}}}
  void saveResult()throws Exception{String name="Animated Inventory.mcpack";if(outputTree==null){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,3);return;}try{Uri doc=DocumentsContract.createDocument(getContentResolver(),outputTree,"application/octet-stream",name);try(OutputStream o=getContentResolver().openOutputStream(doc)){o.write(result);}}catch(Exception e){outputTree=null;getPreferences(0).edit().remove("outputTree").apply();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,3);}}
  byte[] read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();return out.toByteArray();}
  int gifFrames(byte[] raw){int i=0,n=0;while(i<raw.length){int b=raw[i++]&255;if(b==0x3b)break;if(b==0x2c){if(i+9>raw.length)break;int packed=raw[i+8]&255;i+=9;if((packed&128)!=0)i+=3*(1<<((packed&7)+1));if(i>=raw.length)break;i++;while(i<raw.length){int s=raw[i++]&255;if(s==0)break;i+=s;}n++;}else if(b==0x21){if(i>=raw.length)break;i++;while(i<raw.length){int s=raw[i++]&255;if(s==0)break;i+=s;}}else break;}return Math.max(1,n);}
  byte[] makePack()throws Exception{byte[] raw=read(gif);Movie m=Movie.decodeByteArray(raw,0,raw.length);if(m==null)throw new Exception();int count=Math.min(11,gifFrames(raw)),dur=Math.max(100,m.duration()),fps=Math.max(2,Math.min(30,Math.round(1000f*count/dur))),w=352,h=332;Bitmap strip=Bitmap.createBitmap(w*count,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(strip);Paint p=new Paint(3);for(int n=0;n<count;n++){m.setTime((int)(dur*n/(float)count));c.save();c.scale((float)w/m.width(),(float)h/m.height());m.draw(c,0,0,p);c.restore();}Bitmap lines=BitmapFactory.decodeStream(getAssets().open("template/textures/ui/inventory_lines.png"));for(int n=0;n<count;n++)c.drawBitmap(lines,null,new Rect(n*w,0,n*w+w,h),p);ByteArrayOutputStream stripOut=new ByteArrayOutputStream();strip.compress(Bitmap.CompressFormat.PNG,100,stripOut);Bitmap packIcon=Bitmap.createBitmap(256,256,Bitmap.Config.ARGB_8888);Canvas ic=new Canvas(packIcon);m.setTime(0);ic.scale(256f/m.width(),256f/m.height());m.draw(ic,0,0,p);ByteArrayOutputStream iconOut=new ByteArrayOutputStream();packIcon.compress(Bitmap.CompressFormat.PNG,100,iconOut);Map<String,byte[]> files=new HashMap<>();loadAssets(files,"template","");files.put("textures/ui/inventory_flipbook.png",stripOut.toByteArray());files.put("pack_icon.png",iconOut.toByteArray());String common=new String(files.get("ui/chouiui/chouiui_common.json"),"UTF-8").replaceAll("\\\"frame_count\\\"\\s*:\\s*\\d+","\\\"frame_count\\\": "+count).replaceAll("\\\"fps\\\"\\s*:\\s*\\d+","\\\"fps\\\": "+fps);files.put("ui/chouiui/chouiui_common.json",common.getBytes("UTF-8"));ByteArrayOutputStream out=new ByteArrayOutputStream();ZipOutputStream z=new ZipOutputStream(out);for(Map.Entry<String,byte[]>e:files.entrySet()){z.putNextEntry(new ZipEntry(e.getKey()));z.write(e.getValue());z.closeEntry();}z.close();return out.toByteArray();}
  void loadAssets(Map<String,byte[]>out,String root,String rel)throws Exception{String[] list=getAssets().list(root+(rel.isEmpty()?"":"/"+rel));for(String s:list){String r=rel.isEmpty()?s:rel+"/"+s,p=root+"/"+r;String[] sub=getAssets().list(p);if(sub.length>0)loadAssets(out,root,r);else{InputStream in=getAssets().open(p);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);out.put(r,o.toByteArray());}}}
}
